### ISSUE TITLE
Tetris Pieces Consistent?

### ISSUE THREAD

**Issue by sptobey** [mbinsfeld/Tetrace#4]
I noticed that some of the prefabs for tetris pieces were not like the others, particularly the "long" and "square" pieces.  I just wanted to make sure that the colliders were okay, since the game board grid pieces (and other things) rely on the tetris piece colliders to make things happen.

**Comment by mbinsfeld** [comment]
All of the prefabs are the same as far as I can tell. When was the last
time that you pulled from upstream? Each individual cube now has its own
box collider so that the reParenting script works. I didn't see anything in
your code that this would effect. The components are not all in the same
order but all of the components should be the same on each gameObject that
is part of a tetris piece. Does each cube having its own collider break
anything that you did?

sent from mobile.

**Comment by sptobey** [comment]
Well, I'm not sure what is the cause, but when I pulled the new code, multiple things no longer work.  The game grid doesn't detect collisions anymore, the Pieces can can overlap again, and the grid doesn't detect if it is full.  I'm looking into it.

**Comment by sptobey** [comment]
I think I found the problem.  The Cubes in the pieces were set to kinematic, and the physics engine was ignoring collisions with them.  The only problem with the re-parenting is that only the parent needs to be moved when reverting the position of a tetris piece.  I think I can fix it.

**Comment by mbinsfeld** [comment]
So the second piece down on the orange piece is missing all the scripts
that it needs. I'd put them on there and push, but I don't want to cause
merge conflicts because I know you are working with that stuff.

**Comment by sptobey** [comment]
You are right, I changed that and fixed the prefabs.  I'll Merge as soon as I modify the overlap script.
